python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:B ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu G:G ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:K ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:p ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu G:S ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:R ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu D:k ensembl /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:B ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu G:G ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:K ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:p ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu G:S ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu P:R ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
python /gpfs/user/aic/kobas-3.0.0/src/kobas/gmt/getGmt.py mmu D:k ncbigene /gpfs/user/aic/kobas-3.0.0//gmt/
