##only keep species appearing in at least 100 lines
reactome_organisms = {
    'Arabidopsis thaliana':       'ath',
    'Bos taurus':                 'bta',
    'Caenorhabditis elegans':     'cel',
    'Canis familiaris':           'cfa',
    'Danio rerio':                'dre',
    'Dictyostelium discoideum':   'ddi',
    'Drosophila melanogaster':    'dme',
    'Escherichia coli':           'eco',
    'Gallus gallus':              'gga',
    'Homo sapiens':               'hsa',
    'Mus musculus':               'mmu',
    'Mycobacterium tuberculosis': 'mtu',
    'Oryza sativa':               'osa',
    'Plasmodium falciparum':      'pfa',
    'Rattus norvegicus':          'rno',
    'Saccharomyces cerevisiae':   'sce',
    'Schizosaccharomyces pombe':  'spo',
    'Staphylococcus aureus N315': 'sau',
    'Sus scrofa':                 'ssc',
    'Taeniopygia guttata':        'tgu',
    'Xenopus tropicalis':         'xtr'}
