# Aadjust these parameters according to your project
PROJECT: example_data
READSPATH: project/example_data/fastq
SAMPLES: configs/samples.tsv
END: single
OUTPUTPATH: project/example_data/output
GENOME: project/example_data/ref/At10.dna.fa
ANNOTATION: project/example_data/ref/At10_new.gtf
CONTROL: ["root"]
TREAT: ["shoot"]
SPEICE_ABBREVIATION: ath

# ================== Select the software of the workflow ==================
TRIM: fastp # [fastp, cutadapt]
ADAPTER: AGATCGGAAGAGC # for SE_cutadapt or fastp. #ADAPTER_a: AGATCGGAAGAGC #adapter_A: GCTCTTCCGATCT for PE_cutadapt
ALIGN: hisat2 # [hisat2, STAR]
BIGWIG: ["no"] # [yes, no]
DEA: DESeq2 # [DESeq2, edgeR, limma]
QUANTIFY: featureCounts #[featureCounts, htseq]
THREAD: "10" # The number of threads
TIME: "5" # The latency for running individual rules programs in main.py


